### PR TITLE
feat: add sub-package "presets"

### PR DESCRIPTION
**Pull request by RebeccaStevens**
```ts
import { deepmergeDefined } from "deepmerge-ts/presets";
```

### CODE REVIEW

**Comment by fatihaziz** [comment]
I have test it and somehow it will rise another question,
what if we want modify mergeArray to false?

some thing like this:
```
const x = {
 arrays: [1,2,3],
 keyA: "A",

const y = {
 arrays: [4.5.6].
 keyA: undefined,
}

const expected = {
 arrays: [4,5,6],
 keyA: "A",
}

const merged = deepmergeDefined(x,y)
// actual result of merged:
//{
// arrays: [1,2,3,4,5,6],
// keyA: "A",
//}

```

**Comment by RebeccaStevens** [comment]
In order to keep compatibility with older versions of ts and projects not using `"moduleResolution": "Node12"`, I might just make the presets also available via `import { presets } from "deepmerge-ts"`

**Comment by RebeccaStevens** [comment]
We'd need to add lazy evaluation in order to support something like:

> ```ts
> const merged = deepmergeDefined(x,y).options({
>   mergeArray: false
> })
> ```

But that syntax is pretty similar to just `deepmergeDefined(...args)(options)` which is just `deepmergeCustom` but with the functions' order swapped.

I think the best solution would probably be to also export the preset options so that users can pick and choose preset functions to built there own custom merge.

**Comment by fatihaziz** [comment]
> I think the best solution would probably be to also export the preset options so that users can pick and choose preset functions to built there own custom merge.

I like to see how it will be, because I can't imagine the syntax.

**Comment by fatihaziz** [comment]
I got rollup error when trying to build the package,
image

after debugging, I found that on windows, the path is not normalized so it always throw "Unknown Import"

Solution, adding a normalizer path to change the path to UNIX like pattern.
image

after that it runs normaly
image

could you check it?

**Comment by RebeccaStevens** [comment]
Does `path.normalize` not work?

**Comment by fatihaziz** [comment]
> Does `path.normalize` not work?

nope, it only removing ".." but not convert the pattern to UNIX

**Comment by fatihaziz** [comment]
```

// credits to: https://www.npmjs.com/package/slash
export const pathNormalize = (pathString: string) => {
  const isExtendedLengthPath = pathString.startsWith("\\\\?\\");
  // eslint-disable-next-line no-control-regex, require-unicode-regexp
  const hasNonAscii = /[^\u0000-\u0080]+/.test(pathString);

  if (isExtendedLengthPath || hasNonAscii) {
    return pathString;
  }

  return pathString.replaceAll("\\", `/`);
};
```

here the codes for normalize the path,
I modify it from https://www.npmjs.com/package/slash since its discontinued

**Comment by RebeccaStevens** [comment]
Closing in favor of #315

**Pull request closed without merging**
