### PR TITLE
feat: treat module imports as records

### LINKED ISSUE #133: Please support [Module: null prototype]
Does not work with imported modules.

#### For example:
```js
// module-a.js file
export const age = 30;

// module-b.js file
export const name = 'alice';

// deep merge
const a = await import('./module-a.js'); // [Module: null prototype] { age: 30 }
const b = await import('./module-b.js'); // [Module: null prototype] { name: 'alice' }
const merged = deepmerge(a, b);
```

#### Actual merge result
```js
{
  name: 'alice'
}

```

#### Expected merge result
```js
{
  age: 30,
  name: 'alice'
}
```

### PR DESCRIPTION
**Pull request by RebeccaStevens**
fix #133

### CODE REVIEW

**Comment by fatihaziz** [comment]
I think we need to add test merging involve with `Object.create(null)` and see how it behave. Because the changes of `isPlainObject` to `isRecord`.

**Comment by RebeccaStevens** [comment]
> I think we need to add test merging involve with `Object.create(null)` and see how it behave. Because the changes of `isPlainObject` to `isRecord`.

Tests created

**Comment by fatihaziz** [comment]
> > I think we need to add test merging involve with `Object.create(null)` and see how it behave. Because the changes of `isPlainObject` to `isRecord`.
> 
> Tests created

Looks great!
Thank you

**Comment by RebeccaStevens** [comment]
Fixed `isRecord` tests.

**Pull request merged**
